### ISSUE TITLE
Broken in 0.5.1 when using Partitioner

### ISSUE THREAD

**Issue by kristijanhusak** [percolatestudio/publish-counts#53]
Hi,

Today i updated Meteor to the latest version.
I am using [Partitioner](https://github.com/mizzao/meteor-partitioner) in my project. It is using `_groupId` property in documents to allow grouping data. After the update, counts are started to fail. I get these messages in the console:
```
W20150804-14:13:37.211(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:13:37.212(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:13:37.221(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:13:37.225(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:13:37.235(2)? (STDERR) publish-counts: unused fields detected in cursor fields option { _groupId: 0 }
I20150804-14:13:37.290(2)? Exception from sub calculateTasksTime id 85639iS5gCWLAshhy MinimongoError: You cannot currently mix including and excluding fields.
I20150804-14:13:37.290(2)?     at MinimongoError (packages/minimongo/minimongo.js:53:1)
I20150804-14:13:37.290(2)?     at packages/minimongo/projection.js:75:1
I20150804-14:13:37.290(2)?     at Array.forEach (native)
I20150804-14:13:37.290(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150804-14:13:37.290(2)?     at projectionDetails (packages/minimongo/projection.js:69:1)
I20150804-14:13:37.290(2)?     at Function.LocalCollection._compileProjection (packages/minimongo/projection.js:12:1)
I20150804-14:13:37.291(2)?     at new OplogObserveDriver (packages/mongo/oplog_observe_driver.js:87:1)
I20150804-14:13:37.291(2)?     at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1164:1)
I20150804-14:13:37.291(2)?     at [object Object].mongoConnectionProto._observeChanges (packages/meteorhacks:kadira/lib/hijack/wrap_observers.js:61:1)
I20150804-14:13:37.291(2)?     at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:854:1)
I20150804-14:13:37.377(2)? Kadira: successfully authenticated
I20150804-14:14:10.291(2)? Kadira: completed instrumenting the app
I20150804-14:14:10.322(2) (synced-cron-server.js:52) SyncedCron: scheduled "Send reminder to users for weekly review on Friday at 3 PM" next run @Fri Aug 07 2015 15:00:00 GMT+0200 (CEST)
=> Meteor server restarted
W20150804-14:14:10.509(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:14:10.514(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:14:10.523(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
W20150804-14:14:10.525(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }

```

I noticed that only fields required for counting are fetched from database, and other are omitted. I totally support that, but it breaks in this situation. After i downgrade it to 0.4.0 everything got back to normal.

I suggest adding a property to options (4th parameter) that will allow passing in fields that should not be omitted. For example:
```javascript
  var tasks = Task.find({user: user._id});
  Counts.publish(this, 'calculateTasksTime', tasks, {
    countFromField: 'time', 
    fields: ['_groupId']
  });

```

**Comment by tmeasday** [comment]
I'm not sure I understand the purpose of adding extra fields? Is `_groupId` not irrelevant to the count?

**Comment by kristijanhusak** [comment]
It is irrelevant. I misunderstood the way the counting is done inside the package.
But still the problem is here. Do you know how can i fix it?

**Comment by boxofrox** [comment]
I hadn't expected middleware between publish-count and the Meteor Collection cursor when I wrote the cursor field optimizer, but I think there are a couple ways to fix this, @kristijanhusak .

1. Add a field specifier to your query.  You should see `publish-counts: unused fields detected in cursor fields option. { _groupId: 0 }` instead of the `removed` variant.
    ```js
    var tasks = Task.find({user: user._id}, {fields: {_groupId: true}});
    Counts.publish(this, 'calculateTasksTime', tasks, {
      countFromField: 'time'
    });
    ```

2. Add a field specifier to your query and use an accessor function.  No warnings will appear unless you fail to define a field accessor.
    ```js
    var tasks = Task.find({user: user._id}, {fields: {_groupId: true}});
    Counts.publish(this, 'calculateTasksTime', tasks, {
      countFromField: function (doc) { return doc.time; }
    });
    ```

Let me know how that works out.

**Comment by kristijanhusak** [comment]
First solution is not working for me, but second is working. I only changed string `time` with the function, without specifying the fields.

Thanks!

**Comment by kristijanhusak** [comment]
@tmeasday @boxofrox 

Only one a bit annoying issue with this is that i constantly get warnings in the console:
```
W20150807-13:23:45.353(2)? (STDERR) publish-counts: unused fields removed from cursor fields option. { _groupId: 0 }
```
Is there any chance to move that to some debug block which can be enabled be developer if needed?
