### ISSUE TITLE
Undefined object exception when using local collections.

### ISSUE THREAD

**Issue by boxofrox** [percolatestudio/publish-counts#61]
In [#35](https://github.com/percolatestudio/publish-counts/issues/35#issuecomment-133327855), @jjman505 writes:

> So I tried the example from @boxofrox, with minor changes here: 
> https://gist.github.com/jjman505/edd91510eeb8b27d9853
>
> I get the following error:
> ```
> Exception from sub pendingReview id CCtvre3cA73bFozdb TypeError: Cannot read property 'options' of undefined
     at Object.Counts.publish (packages/tmeasday:publish-counts/publish-counts.js:42:1)
     at [object Object]._handler (app/server/publications.js:51:16)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
     at packages/ddp/livedata_server.js:546:1
> ```

A local collection is defined as `new Mongo.Collection(null)` (see [Meteor Docs](http://docs.meteor.com/#/basic/Mongo-Collection)).

Apparently local collections don't define a `_cursorDescription` property on their cursors.

Suggested fix: skip field specifier optimization if `_cursorDescription` is undefined.

PR to follow after consensus.

CC @tmeasday, @dburles

**Comment by tmeasday** [comment]
Makes sense to me
