### ISSUE TITLE
Exception. RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by puedesleerlo** [percolatestudio/publish-counts#93]
Hello! I got this error on Meteor 1.4.2.3

```
I20170110-21:57:00.978(-5)? Exception from sub tools4Loans id 3bDeoYXE8mbodYkqW RangeError: Maximum call stack size exceeded
I20170110-21:57:00.979(-5)?     at [object Object].toString (native)
I20170110-21:57:00.979(-5)?     at Function._.(anonymous function) [as isArguments] (packages/underscore.js:1059:23)
I20170110-21:57:00.979(-5)?     at Object.EJSON.clone (packages/ejson.js:502:25)
I20170110-21:57:00.980(-5)?     at packages/ejson.js:521:22
I20170110-21:57:00.980(-5)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20170110-21:57:00.980(-5)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20170110-21:57:00.981(-5)?     at packages/ejson.js:521:22
I20170110-21:57:00.981(-5)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20170110-21:57:00.981(-5)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20170110-21:57:00.982(-5)?     at packages/ejson.js:521:22
```

This is the publication
```
Meteor.publish('tools4Loans', function(options: Options){
    Counts.publish(this, 'number', ToolsCollection.find(), { noReady: true });
    return ToolsCollection.find({}, options);
  });
```

this is the client subscription
```
this.totalsizeSub = MeteorObservable.autorun().subscribe(() => {
      this.tools4LoansSize = Counts.get('number');
      this.paginationService.setTotalItems(this.paginationService.defaultId(), this.tools4LoansSize);
    });
```

I would appreciate any help. Thanks!

**Comment by puedesleerlo** [comment]
The package MongoObservable was the problem. It is a wrapper of Mongo and the new methods don't work. The problem was resolved changing ToolsCollection.find() to ToolsCollection.collection.find(). ToolsCollection is an instance of MongoObservable: https://github.com/Urigo/meteor-rxjs
