### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 24thsaint** [percolatestudio/publish-counts#94]
Hi. Thank you for this package percolatestudio. I am having errors when using it. I'm using it this way:

Server-side publication
```javascript
import { Counts } from 'meteor/tmeasday:publish-counts'
...
Meteor.publish('books', function () {
  Counts.publish(this, 'booksCount', Book.collection.find({}))
  return Book.collection.find({})
})
```

Client-side
```javascript
import { Counts } from 'meteor/tmeasday:publish-counts'
...
  constructor() {
      MeteorObservable.subscribe('books').subscribe(() => {
        console.log(Counts.get('booksCount'))
      })
  }
```
But then I am getting this error:
```
I20170113-00:32:01.823(8)? Exception from sub books id hCMbYC4KPwbBkKcxn RangeError: Maximum call stack size exceeded
I20170113-00:32:01.824(8)?     at Object.EJSON.isBinary (packages/ejson.js:383:27)
I20170113-00:32:01.824(8)?     at Object.EJSON.clone (packages/ejson.js:494:13)
I20170113-00:32:01.825(8)?     at packages/ejson.js:521:22
I20170113-00:32:01.825(8)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20170113-00:32:01.825(8)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20170113-00:32:01.825(8)?     at packages/ejson.js:521:22
I20170113-00:32:01.825(8)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20170113-00:32:01.825(8)?     at Object.EJSON.clone (packages/ejson.js:520:5)
I20170113-00:32:01.825(8)?     at packages/ejson.js:521:22
I20170113-00:32:01.826(8)?     at Function._.each._.forEach (packages/underscore.js:147:22)
```

I have Meteor version: 1.4.2.3

**Comment by 24thsaint** [comment]
Ohmygod I am so sorry I just found this solution: 
https://github.com/percolatestudio/publish-counts/issues/93

Resolved, thanks. (Can someone please delete this issue? T_T It was an honest mistake on my part.)

**Comment by boxofrox** [comment]
Nope, no _delete issue_ here.  Guess this will have to be a permanent record :stuck_out_tongue:.  Glad you found the solution.

Are you also using meteor-rxjs? Or did you run into this error with another package that wraps around mongo?

Cheers
